### ISSUE TITLE
Ingore the hatred from StackExchange

### ISSUE THREAD

**Issue by Dillybob92** [voodooattack/nexusjs#1]
The hatred for JavaScript that they have is incredible. Keep up the good work and do whatever the fuck you want to do. Write whatever you want, don't let their negative, subtle, asinine remarks get in your way.  I was appalled reading the thread and seeing all the hate towards JavaScript. They spend more time complaining about JS than actually doing things constructive in their lives. It's pretty sad.

**Comment by voodooattack** [comment]
Thank you. I'm still working and plan to work on this in my spare time. I actually enjoy coding this and I hope that one day it'll pick up and become a new standard tool in the hands of JavaScript programmers everywhere.

The hate I get is natural, because people are resistant to change, and you have to convince them to see it your way. Trust me when I say that they will, in time. The performance gains from multithreading in JS is significant, and once the benchmarks hit the web, we'll be looking at a whole new world. 

Thanks for your kind words. You can't possibly know how much your support means to me.

**Comment by bigopon** [comment]
@Dillybob92 , @voodooattack  May I know the link to thread in stackexchange for a read ?

**Comment by voodooattack** [comment]
@bigopon http://programmers.stackexchange.com/questions/315454/what-are-the-drawbacks-of-making-a-multi-threaded-javascript-runtime-implementat

**Comment by bigopon** [comment]
Actually it's not only negative. The comments vary from facts to denials to supports. Please continue your work.

**Comment by voodooattack** [comment]
Thank you. I will. :+1:
